### ISSUE TITLE
WHERE guard for UUID keys on empty on operand type, not column type — string-spelled/YAML filters unguarded

### ISSUE THREAD

**Issue by spiritEcosse** [spiritEcosse/storm#622]
## Problem

#609 fixed the silent empty-UUID auto-generate bug in `.where()`/`.having()` filter comparisons — but only for operands actually spelled as `storm::UUID`. `bind_filter_value`/`bind_uuid_where` (`src/orm/utilities.cppm`) dispatch on the **operand's** C++ type, not the **column's** declared type. A plain string operand against a UUID column bypasses the guard entirely and reproduces #609's original symptom verbatim:

```cpp
qs.where(fields::UuidKeyedDoc.id == "").erase().execute();
// binds a raw, unvalidated empty string; SQLite matches zero rows silently,
// PostgreSQL errors with "invalid input syntax for type uuid" instead of
// #609's clear "UUID comparison value must be explicitly set" message.
```

This is not hypothetical: `shared/query_builder.hpp` (the YAML/JSON filter path) only ever produces string/int/double/bool operands — `typed_value_as` has no `storm::UUID` branch — so a YAML condition `{field: id, op: "==", value: ""}` against a UUID column is completely unguarded by #609's fix.

## Root cause

`make_comparison_expr`/`make_in_expr` (`src/orm/where.cppm`) take `const std::string& field_name` and have already discarded the `std::meta::info` member reflection by the time they run — the WHERE expression system is intentionally type-erased on the column side. A column-type-aware guard means threading the field's declared `FieldType` through `Field<M>`'s comparison-operator surface into these builders, which is a materially larger design change than #609's operand-side fix.

## Related, same root cause: `std::optional<T>` operand hard-errors instead of rejecting cleanly

Found during #609's review: `ComparableOperand`/`OrderableOperand` gate on `utilities::BindableType`, which accepts `std::optional<T>` (it recurses through `is_bindable_v`). But `ExpressionVariant` has **no** `ComparisonExpr<std::optional<T>>`/`InExpression<std::optional<T>>` arm for *any* `T` — so a `std::optional<T>` operand passes the compile-time constraint and then hard-errors deep inside `std::make_shared<ExpressionVariant>(...)` (`no matching function for call to '__construct_at'`) instead of failing cleanly at the constraint. Same class of bug as #609's `.between()` regression (constraint surface broader than the variant arm set), just for optional operands instead of UUID ones. Whoever fixes the column-type-aware guard here should tighten this gap in the same pass — one issue, one commit, two symptoms.

## Fix (undecided, needs design)

- Thread the column's declared `FieldType` into `make_comparison_expr`/`make_in_expr`/`make_between_expr` so a `storm::UUID`-typed column normalizes a string/YAML operand through `storm::UUID{...}` (and hence #609's validation/empty-rejection) regardless of how the caller spelled it.
- Add a `typed_value_as` branch (or equivalent) in `shared/query_builder.hpp` for `storm::UUID` columns.
- Either add `ComparisonExpr<std::optional<T>>`/`InExpression<std::optional<T>>` variant arms, or narrow `ComparableOperand` to reject `std::optional<T>` operands at the constraint (matching how #609 narrowed `OrderableOperand` for UUID+ordering) so the failure is a clear compile-time rejection instead of a deep instantiation error.

## Context

Found by `storm-sql-reviewer` during #609's review (two review passes). Pre-existing, not introduced by #609 — #609 only closed the `storm::UUID{}`-spelled-operand case.

Related: #609, #608, #573.
